# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM payara/server-full:162

COPY target/JEAKwetter-1.0-SNAPSHOT.war /opt/payara41/glassfish/domains/domain1/autodeploy

EXPOSE 8080

